# permissions for end users to edit calculators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: helloworld
    app.kubernetes.io/managed-by: kustomize
  name: calculator-editor-role
rules:
- apiGroups:
  - webapp.helloworld.dqo.me
  resources:
  - calculators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webapp.helloworld.dqo.me
  resources:
  - calculators/status
  verbs:
  - get
